# Generated by Django 3.0.8 on 2020-08-10 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=4)),
                ('course_number', models.CharField(max_length=4)),
                ('course_code', models.CharField(max_length=8)),
                ('course_title', models.CharField(max_length=150)),
                ('course_name', models.CharField(max_length=150)),
                ('course_description', models.CharField(max_length=600)),
                ('department', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('course_level', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=10)),
                ('departments', models.CharField(max_length=100)),
                ('faculty_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='coursereview.Course')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'db_table': 'faculty',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=10)),
                ('faculty_id', models.CharField(max_length=10)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='coursereview.Course')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('helpful', models.IntegerField(default=0)),
                ('not_helpful', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='coursereview.Course')),
            ],
            options={
                'verbose_name': 'Course Review',
                'verbose_name_plural': 'Course Reviews',
                'db_table': 'coursereviews',
            },
        ),
    ]
